# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/all.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  releaseName: tempo
  interval: 1m
  chart:
    spec:
      chart: tempo-distributed
      version: "1.52.8"
      sourceRef:
        kind: HelmRepository
        name: tempo-distributed
        namespace: flux-system
  values:
    gateway:
      enabled: true
    minio:
      enabled: true
    storage:
      trace:
        backend: s3
        s3:
          access_key: "grafana-tempo" # todo: change it later
          secret_key: "supersecret" # todo: change it later
          bucket: "tempo-traces"
          endpoint: "tempo-minio.monitoring.svc.cluster.local:9000"
          insecure: true
    traces:
      otlp:
        http:
          enabled: true
        grpc:
          enabled: true
    distributor:
      config:
        log_received_spans:
          enabled: true
        log_discarded_spans:
          enabled: true
