# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/all.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  releaseName: grafana
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: 9.*
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    replicas: 2
    # persistence:
    #   enabled: true
    #   size: 10Gi
