# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/all.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.138.1"
      sourceRef:
        kind: HelmRepository
        name: opentelemetry-collector
        namespace: monitoring
  # https://opentelemetry.io/docs/platforms/kubernetes/helm/collector/
  values:
    mode: deployment
    image:
      repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
    ports:
      jaeger-compact:
        enabled: false
      jaeger-thrift:
        enabled: false
      jaeger-grpc:
        enabled: false
      zipkin:
        enabled: false
      # # Enable this if scraping approach is used.
      # prometheus:
      #   enabled: true
      #   containerPort: 8889
      #   servicePort: 8889
    config:
      receivers:
        jaeger: null
        prometheus: null
        zipkin: null
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"
      exporters:
        # Send to prometheus' otlp receiver.
        # Prerequisites: prometheus enables "web.enable-otlp-receiver".
        otlphttp/prometheus:
          endpoint: "prometheus-server.monitoring.svc.cluster.local/api/v1/otlp/v1/metrics"
        # # Should be scraped by prometheus.
        # prometheus:
        #   endpoint: "0.0.0.0:8889"
        #   namespace: "otelcol"
        otlphttp/loki:
          endpoint: "loki.monitoring.svc.cluster.local:3100/otlp"
        otlp/tempo:
          endpoint: "tempo.monitoring.svc.cluster.local:4317"
          tls:
            insecure: true
      service:
        pipelines:
          metrics:
            receivers: [otlp]
            exporters: [otlphttp/prometheus]
          logs:
            receivers: [otlp]
            exporters: [otlphttp/loki]
          traces:
            receivers: [otlp]
            exporters: [otlp/tempo]
