# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/all.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-collector
spec:
  interval: 1m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.130.*"
      sourceRef:
        kind: HelmRepository
        name: opentelemetry-collector
        namespace: monitoring
  # https://opentelemetry.io/docs/platforms/kubernetes/helm/collector/
  values:
    mode: daemonset
    image:
      repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
    ports:
      jaeger-compact:
        enabled: false
      jaeger-thrift:
        enabled: false
      jaeger-grpc:
        enabled: false
      zipkin:
        enabled: false
    config:
      receivers:
        jaeger: null
        prometheus: null
        zipkin: null
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"
      exporters:
        # prometheusremotewrite:
        #   endpoint: "http://prometheus-server.monitoring.svc.cluster.local/api/v2/write"
        otlphttp/loki:
          endpoint: "http://loki.monitoring.svc.cluster.local:3100/otlp"
        otlp/tempo:
          endpoint: "tempo.monitoring.svc.cluster.local:4317"
          tls:
            insecure: true
      service:
        pipelines:
          metrics:
            receivers: [otlp]
            exporters: [debug]
            # exporters: [prometheusremotewrite]
          logs:
            receivers: [otlp]
            exporters: [otlphttp/loki]
          traces:
            receivers: [otlp]
            exporters: [otlp/tempo]
